name: that games ux
remote_theme: pages-themes/tactile@v0.2.0
plugins: 
- jekyll-remote-theme
include:
  - _posts/*
  
title: "That Game's UX"
description: Because gamers are users too
permalink: /:title
