name: that games ux
theme: minima
include:
  - _posts/*
  - _posts/**/*
title: That Game's UX
description: Because gamers are users too
permalink: /:title
site.author.name: "Mark DeHate"
logo: images/tgux-logo.svg
